sudo: required
services:
  - docker

before_install:
  - docker build -t annamart/react-test -f ./client/Dockerfile.dev ./client


script:
#  - docker run annamart/react-test npm test -- --coverage
  - docker run --env CI=true annamart/react-test npm run test


after_success:
  - docker build -t annamart/multi-client ./client
  - docker build -t annamart/mult-nginx ./nginx
  - docker build -t annamart/mult-server ./server
  - docker build -t annamart/mult-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push annamart/multi-client
  - docker push annamart/multi-nginx
  - docker push annamart/multi-server
  - docker push annamart/multi-worker
